# Generated by Django 4.2.7 on 2023-11-28 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-fixed', '-time_create'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью поста'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-fixed', '-time_create', 'status'], name='app_article_fixed_e300bf_idx'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='app_articles',
        ),
    ]
